// ── notif-copy.js ─────────────────────────────────────────────────────────────
// Shared push notification copy for all 7 app languages.
// Used by notify-reminders, notify-pipeline, and notify-weekly.

const COPY = {
  en: {
    reminderFallback:       "Time to follow up.",
    staleTitle:             "Keep your pipeline moving",
    staleBody:              "Your framework is ready — don't let momentum slip.",
    followUpBody:           "10 days since you applied — time to follow up?",
    timelineTitle:          (days)                   => `${days}-day check-in`,
    timelineBodyApplied:    (scored, applied, left)  => `${scored} roles scored · ${applied} applied · ${left}d left in your window.`,
    timelineBodyNoApps:     (scored, pct)            => `${scored} roles scored · ${pct}% through your window · no applications yet.`,
    weeklyTitle:            (bestLine)               => `Weekly recap${bestLine}`,
    weeklyBestLine:         (score)                  => ` · Best match: ${score}`,
    weeklyBody:             (scoredLine, flightLine) => `${scoredLine} this week. ${flightLine}`,
    weeklyScored:           (n)                      => n === 1 ? "1 role scored" : `${n} roles scored`,
    weeklyActive:           (n)                      => `${n} active in your pipeline.`,
    weeklyNone:             "Keep your pipeline moving.",
  },
  es: {
    reminderFallback:       "Momento de hacer seguimiento.",
    staleTitle:             "Mantén tu pipeline activo",
    staleBody:              "Tu framework está listo — no pierdas el impulso.",
    followUpBody:           "10 días desde que aplicaste — ¿hora de dar seguimiento?",
    timelineTitle:          (days)                   => `Check-in de ${days} días`,
    timelineBodyApplied:    (scored, applied, left)  => `${scored} roles evaluados · ${applied} aplicados · ${left}d restantes.`,
    timelineBodyNoApps:     (scored, pct)            => `${scored} roles evaluados · ${pct}% de tu ventana · sin aplicaciones aún.`,
    weeklyTitle:            (bestLine)               => `Resumen semanal${bestLine}`,
    weeklyBestLine:         (score)                  => ` · Mejor match: ${score}`,
    weeklyBody:             (scoredLine, flightLine) => `${scoredLine} esta semana. ${flightLine}`,
    weeklyScored:           (n)                      => n === 1 ? "1 rol evaluado" : `${n} roles evaluados`,
    weeklyActive:           (n)                      => `${n} activos en tu pipeline.`,
    weeklyNone:             "Mantén tu pipeline activo.",
  },
  zh: {
    reminderFallback:       "是时候跟进了。",
    staleTitle:             "保持求职进度",
    staleBody:              "你的框架已准备好 — 不要让势头冷却。",
    followUpBody:           "申请已过10天 — 是时候跟进了？",
    timelineTitle:          (days)                   => `${days}天打卡`,
    timelineBodyApplied:    (scored, applied, left)  => `已评分${scored}个职位 · ${applied}个已申请 · 窗口还剩${left}天。`,
    timelineBodyNoApps:     (scored, pct)            => `已评分${scored}个职位 · 完成${pct}% · 暂无申请。`,
    weeklyTitle:            (bestLine)               => `每周回顾${bestLine}`,
    weeklyBestLine:         (score)                  => ` · 最佳匹配：${score}`,
    weeklyBody:             (scoredLine, flightLine) => `本周${scoredLine}。${flightLine}`,
    weeklyScored:           (n)                      => `已评分${n}个职位`,
    weeklyActive:           (n)                      => `${n}个职位跟进中。`,
    weeklyNone:             "保持求职进度。",
  },
  fr: {
    reminderFallback:       "C'est le moment de faire un suivi.",
    staleTitle:             "Gardez votre pipeline actif",
    staleBody:              "Votre framework est prêt — ne laissez pas l'élan retomber.",
    followUpBody:           "10 jours depuis votre candidature — temps de relancer ?",
    timelineTitle:          (days)                   => `Point à ${days} jours`,
    timelineBodyApplied:    (scored, applied, left)  => `${scored} rôles évalués · ${applied} candidatures · ${left}j restants.`,
    timelineBodyNoApps:     (scored, pct)            => `${scored} rôles évalués · ${pct}% de votre fenêtre · aucune candidature.`,
    weeklyTitle:            (bestLine)               => `Récap hebdomadaire${bestLine}`,
    weeklyBestLine:         (score)                  => ` · Meilleur match : ${score}`,
    weeklyBody:             (scoredLine, flightLine) => `${scoredLine} cette semaine. ${flightLine}`,
    weeklyScored:           (n)                      => n === 1 ? "1 rôle évalué" : `${n} rôles évalués`,
    weeklyActive:           (n)                      => `${n} actifs dans votre pipeline.`,
    weeklyNone:             "Gardez votre pipeline actif.",
  },
  ar: {
    reminderFallback:       "حان وقت المتابعة.",
    staleTitle:             "حافظ على زخم بحثك",
    staleBody:              "إطارك جاهز — لا تدع الزخم يتراجع.",
    followUpBody:           "مرّ 10 أيام منذ تقديمك — حان وقت المتابعة؟",
    timelineTitle:          (days)                   => `متابعة يوم ${days}`,
    timelineBodyApplied:    (scored, applied, left)  => `${scored} أدوار مُقيَّمة · ${applied} مُقدَّم عليها · ${left} يوم متبقٍّ.`,
    timelineBodyNoApps:     (scored, pct)            => `${scored} أدوار مُقيَّمة · ${pct}% من نافذتك · لا تقديمات بعد.`,
    weeklyTitle:            (bestLine)               => `ملخص الأسبوع${bestLine}`,
    weeklyBestLine:         (score)                  => ` · أفضل تطابق: ${score}`,
    weeklyBody:             (scoredLine, flightLine) => `${scoredLine} هذا الأسبوع. ${flightLine}`,
    weeklyScored:           (n)                      => n === 1 ? "دور واحد مُقيَّم" : `${n} أدوار مُقيَّمة`,
    weeklyActive:           (n)                      => `${n} نشط في خطوطك.`,
    weeklyNone:             "حافظ على زخم بحثك.",
  },
  vi: {
    reminderFallback:       "Đến lúc theo dõi rồi.",
    staleTitle:             "Duy trì đà tìm việc",
    staleBody:              "Framework của bạn đã sẵn sàng — đừng để đà dừng lại.",
    followUpBody:           "10 ngày kể từ khi bạn ứng tuyển — đã đến lúc theo dõi chưa?",
    timelineTitle:          (days)                   => `Điểm kiểm tra ${days} ngày`,
    timelineBodyApplied:    (scored, applied, left)  => `${scored} vị trí đã đánh giá · ${applied} đã ứng tuyển · còn ${left} ngày.`,
    timelineBodyNoApps:     (scored, pct)            => `${scored} vị trí đã đánh giá · ${pct}% qua khung thời gian · chưa có đơn.`,
    weeklyTitle:            (bestLine)               => `Tóm tắt tuần${bestLine}`,
    weeklyBestLine:         (score)                  => ` · Phù hợp nhất: ${score}`,
    weeklyBody:             (scoredLine, flightLine) => `${scoredLine} tuần này. ${flightLine}`,
    weeklyScored:           (n)                      => n === 1 ? "1 vị trí đã đánh giá" : `${n} vị trí đã đánh giá`,
    weeklyActive:           (n)                      => `${n} đang hoạt động trong pipeline.`,
    weeklyNone:             "Duy trì đà tìm việc.",
  },
  pt: {
    reminderFallback:       "Hora de fazer o acompanhamento.",
    staleTitle:             "Mantenha seu pipeline ativo",
    staleBody:              "Seu framework está pronto — não deixe o ritmo cair.",
    followUpBody:           "10 dias desde a candidatura — hora de fazer o follow-up?",
    timelineTitle:          (days)                   => `Check-in de ${days} dias`,
    timelineBodyApplied:    (scored, applied, left)  => `${scored} vagas avaliadas · ${applied} candidaturas · ${left}d restantes.`,
    timelineBodyNoApps:     (scored, pct)            => `${scored} vagas avaliadas · ${pct}% da sua janela · sem candidaturas ainda.`,
    weeklyTitle:            (bestLine)               => `Resumo semanal${bestLine}`,
    weeklyBestLine:         (score)                  => ` · Melhor match: ${score}`,
    weeklyBody:             (scoredLine, flightLine) => `${scoredLine} esta semana. ${flightLine}`,
    weeklyScored:           (n)                      => n === 1 ? "1 vaga avaliada" : `${n} vagas avaliadas`,
    weeklyActive:           (n)                      => `${n} ativos no seu pipeline.`,
    weeklyNone:             "Mantenha seu pipeline ativo.",
  },
};

export function getCopy(lang) {
  return COPY[lang] || COPY.en;
}
